[project]
authors = ["Dhaiwat Pandya"]
entry = "main.sw"
license = "Apache-2.0"
name = "sway-git-checkout-bug-repro"

[dependencies]
std = { git = "https://github.com/FuelLabs/sway", branch = "feature/fuel-core-0.18" }
